"""
MP-ALOE ingest script for ColabFit VAST database.

Properties
----------
energy: total DFT energy in eV
atomic-forces: forces in eV/Å
cauchy-stress: stress tensor in kBar (Voigt 6-vector), converted to 3x3 matrix
band-gap: Kohn-Sham DFT band gap in eV (present for ~33% of records; 0.0 = metal)

File notes
----------
Source: MP_ALOE_data.jsonl
MP-ALOE is a dataset of nearly 1 million DFT calculations computed with the
r2SCAN meta-generalized gradient approximation, covering 89 elements.
Structures were generated by elemental substitution into prototype structures
from ICSD and Materials Project databases, selected via Query by Committee
active learning, and downsampled with the DIRECT method. A two-stage DFT
workflow was used: initial static PBE calculation, then r2SCAN relaxation for
three ionic steps. Each relaxation contributes 3 frames; 909,792 total frames
from 303,264 relaxations.

Stress is reported as a Voigt 6-vector [σxx, σyy, σzz, σxy, σyz, σzx] in kBar
(VASP/pymatgen convention). Converted to 3x3 symmetric matrix in reader.
"""

import json
import os
from pathlib import Path

from ase import Atoms as AseAtoms
from colabfit.tools.property_definitions import (
    atomic_forces_pd,
    band_gap_pd,
    cauchy_stress_pd,
    energy_pd,
)
from colabfit.tools.vast.configuration import AtomicConfiguration
from colabfit.tools.vast.database import DataManager, VastDataLoader
from colabfit.tools.vast.property import PropertyInfo, PropertyMap
from dotenv import load_dotenv
from vastdb.session import Session

load_dotenv()

access_key = os.getenv("VAST_DB_ACCESS")
access_secret = os.getenv("VAST_DB_SECRET")
endpoint = os.getenv("SPARK_ENDPOINT")
session = Session(access=access_key, secret=access_secret, endpoint=endpoint)

loader = VastDataLoader(
    access_key=access_key,
    access_secret=access_secret,
    endpoint=endpoint,
)
loader.config_table = "ndb.colabfit.dev.co_mpaloe"
loader.config_set_table = "ndb.colabfit.dev.cs_mpaloe"
loader.dataset_table = "ndb.colabfit.dev.ds_mpaloe"
loader.co_cs_map_table = "ndb.colabfit.dev.cs_co_map_mpaloe"

DATASET_ID = "DS_k14lrwu6r2mo_0"
DATASET_NAME = "MP-ALOE"
DESCRIPTION = (
    "MP-ALOE is a dataset of nearly 1 million DFT calculations computed "
    "with the r2SCAN meta-generalized gradient approximation, covering 89 "
    "elements. The dataset was constructed using active learning via Query "
    "by Committee (QBC) and downsampling via the DIRECT method, and "
    "primarily consists of off-equilibrium structures. Initial structures "
    "were generated by elemental substitution into prototype structures from "
    "the ICSD and Materials Project databases (restricted to 2-8 atoms and "
    "up to ternary compositions). QBC used an ensemble of interatomic "
    "potentials (initially MACE-MP-0, CHGNet, and M3GNet, followed by "
    "iteratively trained MACE models) to select structures with energy "
    "uncertainty exceeding 100 meV/atom, force uncertainty exceeding "
    "100 meV/Å, or stress uncertainty exceeding 100 meV/Å³. DIRECT "
    "downsampling reduced approximately 500,000 selected structures to "
    "approximately 125,000 for DFT calculation. Near-equilibrium structures "
    "from the Materials Project (up to 3 elements, up to 32 atoms, "
    "approximately 30,000 structures) were recalculated with identical DFT "
    "settings. A two-stage VASP workflow was applied: an initial static "
    "calculation using PBE, followed by r2SCAN relaxation for three ionic "
    "steps. In total, 909,792 frames from 303,264 structure relaxations are "
    "included. DFT calculations used projector-augmented wave (PAW) "
    "potentials, a 680 eV plane-wave cutoff, and KSPACING=0.2, with "
    "additional parameters from the MP24RelaxSet in pymatgen. Calculations "
    "were managed by the atomate2 workflow package."
)

PUBLICATION = "https://doi.org/10.1038/s41524-025-01834-9"
DATA_LINK = (
    "https://figshare.com/articles/dataset/"
    "MP_ALOE_An_r2SCAN_dataset_for_universal_machine_learning_interatomic_"
    "potentials/29452190"
)
OTHER_LINKS = ["https://arxiv.org/abs/2507.05559"]
PUBLICATION_YEAR = "2025"

AUTHORS = [
    "Matthew C. Kuner",
    "Aaron D. Kaplan",
    "Kristin A. Persson",
    "Mark Asta",
    "Daryl C. Chrzan",
]
LICENSE = "CC-BY-4.0"
DOI = None

DATA_PATH = Path("data") / "MP_ALOE_data.jsonl"


def voigt_6_to_3x3(voigt):
    """
    Convert Voigt 6-vector stress to 3x3 symmetric matrix.
    VASP/pymatgen convention: [σxx, σyy, σzz, σxy, σyz, σzx]
    """
    s = voigt
    return [
        [s[0], s[3], s[5]],
        [s[3], s[1], s[4]],
        [s[5], s[4], s[2]],
    ]


def reader(filepath):
    with open(filepath, "r") as f:
        for i, line in enumerate(f):
            record = json.loads(line)
            struct = record["structure"]
            lattice = struct["lattice"]
            sites = struct["sites"]
            symbols = [site["species"][0]["element"] for site in sites]
            positions = [site["xyz"] for site in sites]
            atoms = AseAtoms(
                symbols=symbols,
                positions=positions,
                cell=lattice["matrix"],
                pbc=lattice["pbc"],
            )
            info = {
                "_name": f"{DATASET_NAME}__{record['mp_aloe_id']}__{i}",
                "energy": record["energy"],
                "forces": record["forces"],
                "stress": voigt_6_to_3x3(record["stress"]),
            }
            if record["bandgap"] is not None:
                info["bandgap"] = record["bandgap"]
            atoms.info = info
            yield AtomicConfiguration.from_ase(atoms)


property_map = PropertyMap([energy_pd, atomic_forces_pd, cauchy_stress_pd, band_gap_pd])

property_map.set_metadata_field("software", "VASP")
property_map.set_metadata_field("method", "DFT-R2SCAN")
property_map.set_metadata_field(
    "input",
    {
        "description": (
            "Two-stage VASP calculation: initial static PBE calculation "
            "followed by r2SCAN meta-GGA relaxation for three ionic steps. "
            "Additional parameters from MP24RelaxSet in pymatgen. "
            "Projector-augmented wave (PAW) potentials. "
            "Plane-wave cutoff energy: 680 eV. KSPACING: 0.2. "
            "Workflows managed by atomate2."
        ),
    },
)

energy_info = PropertyInfo(
    property_name="energy",
    field="energy",
    units="eV",
    original_file_key="energy",
    additional=[("per-atom", {"value": False, "units": None})],
)
force_info = PropertyInfo(
    property_name="atomic-forces",
    field="forces",
    units="eV/angstrom",
    original_file_key="forces",
)
stress_info = PropertyInfo(
    property_name="cauchy-stress",
    field="stress",
    units="kbar",
    original_file_key="stress",
    additional=[("volume-normalized", {"value": False, "units": None})],
)
band_gap_info = PropertyInfo(
    property_name="band-gap",
    field="bandgap",
    units="eV",
    original_file_key="bandgap",
    additional=[("type", {"value": "unknown", "units": None})],
)
property_map.set_properties([energy_info, force_info, stress_info, band_gap_info])
PROPERTY_MAP = property_map.get_property_map()
print(PROPERTY_MAP)

gen = reader(DATA_PATH)

dm = DataManager(
    prop_defs=[energy_pd, atomic_forces_pd, cauchy_stress_pd, band_gap_pd],
    configs=gen,
    prop_map=PROPERTY_MAP,
    dataset_id=DATASET_ID,
    standardize_energy=True,
    read_write_batch_size=10000,
)

dm.load_co_po_to_vastdb(loader, batching_ingest=True, check_existing=False)

dm.create_dataset(
    loader=loader,
    name=DATASET_NAME,
    authors=AUTHORS,
    publication_link=PUBLICATION,
    data_link=DATA_LINK,
    other_links=OTHER_LINKS,
    description=DESCRIPTION,
    data_license=LICENSE,
    publication_year=PUBLICATION_YEAR,
    equilibrium=False,
    date_requested="2026-04-13",
)
