updates = {
    "23-DNPs-RSCDD-2023-Ag": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Ag",
        "colabfit_id": "DS_sweti1zr633p_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Al": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Al",
        "colabfit_id": "DS_7hnw7ifozw6e_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Au": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Au",
        "colabfit_id": "DS_z9wexfuzcghd_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Co": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Co",
        "colabfit_id": "DS_90s3tvcq6odw_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Cu": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Cu",
        "colabfit_id": "DS_akqwr626ce6c_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Ge": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Ge",
        "colabfit_id": "DS_mdxhcsof3677_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-I": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_I",
        "colabfit_id": "DS_cs9b8ynh5szg_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Kr": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Kr",
        "colabfit_id": "DS_th15vfxu0zt8_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Li": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Li",
        "colabfit_id": "DS_pfw021eiieze_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Mg": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Mg",
        "colabfit_id": "DS_i0qwoifqvyoe_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Mo": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Mo",
        "colabfit_id": "DS_gko3hafsxhqi_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Nb": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Nb",
        "colabfit_id": "DS_ks6kg4p4dc7r_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Ni": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Ni",
        "colabfit_id": "DS_fgaklp46p8v4_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Os": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Os",
        "colabfit_id": "DS_5wy20ri8pa17_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Pb": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Pb",
        "colabfit_id": "DS_4nwlpq1hxhcl_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Pd": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Pd",
        "colabfit_id": "DS_0sazt79y2u3p_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Pt": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Pt",
        "colabfit_id": "DS_citzi47quglc_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Re": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Re",
        "colabfit_id": "DS_rt2up46qho48_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Sb": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Sb",
        "colabfit_id": "DS_rbeku5alc1tz_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Sr": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Sr",
        "colabfit_id": "DS_ap7c7w5ekazd_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Ti": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Ti",
        "colabfit_id": "DS_piynt67no7h0_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Zn": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Zn",
        "colabfit_id": "DS_4h6vz85tx0vm_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "23-DNPs-RSCDD-2023-Zr": {
        "new_name": "23-Single-Element-DNPs_RSCDD_2023_Zr",
        "colabfit_id": "DS_kfw8yhto8elz_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/saidigroup/23-Single-Element-DNPs",
        "pub_link": "https://doi.org/10.1039/D3DD00046J",
        "other_links": None,
    },
    "3BPA-isolated-atoms": {
        "new_name": "3BPA_isolated_atoms",
        "colabfit_id": "DS_cfqyihpjqbnu_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "pub_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "other_links": None,
    },
    "3BPA-test-300K": {
        "new_name": "3BPA_test_300K",
        "colabfit_id": "DS_1mz6r381h2rf_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "pub_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "other_links": None,
    },
    "3BPA-test-600K": {
        "new_name": "3BPA_test_600K",
        "colabfit_id": "DS_8whtucrr8vt7_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "pub_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "other_links": None,
    },
    "3BPA-test-1200K": {
        "new_name": "3BPA_test_1200K",
        "colabfit_id": "DS_o7xc8qwpe73x_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "pub_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "other_links": None,
    },
    "3BPA-train-300K": {
        "new_name": "3BPA_train_300K",
        "colabfit_id": "DS_lgoiw2pig8mb_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "pub_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "other_links": None,
    },
    "3BPA-train-mixed": {
        "new_name": "3BPA_train_mixed",
        "colabfit_id": "DS_frt0ryv4g1ka_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "pub_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "other_links": None,
    },
    "3BPA-test-dih-beta120": {
        "new_name": "3BPA_test_dih_beta120",
        "colabfit_id": "DS_8i9qlt9c40dv_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "pub_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "other_links": None,
    },
    "3BPA-test-dih-beta150": {
        "new_name": "3BPA_test_dih_beta150",
        "colabfit_id": "DS_ny2i8g396oud_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "pub_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "other_links": None,
    },
    "3BPA-test-dih-beta180": {
        "new_name": "3BPA_test_dih_beta180",
        "colabfit_id": "DS_r67kld0a1plf_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "pub_link": "https://doi.org/10.1021/acs.jctc.1c00647",
        "other_links": None,
    },
    "AFF_JCP_2022": {
        "new_name": "AFF_JCP_2022",
        "colabfit_id": "DS_294zg1j9lo6j_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/UncertaintyQuantification/AFF/tree/master",
        "pub_link": "https://doi.org/10.1063/5.0088017",
        "other_links": None,
    },
    "Ag-PBE-MSMSE-2021": {
        "new_name": "Ag-PBE_MSMSE_2021",
        "colabfit_id": "DS_wn305sugbeh3_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?name=Ag-PBE&id=3&pageType=datasets",
        "pub_link": "https://doi.org/10.48550/arXiv.2108.06232",
        "other_links": None,
    },
    "AgAu-nanoalloy-MSMSE-2021": {
        "new_name": "AgAu_nanoalloy_MSMSE_2021",
        "colabfit_id": "DS_0soe8tbggpsr_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?name=AgAu-nanoalloy&id=14&pageType=datasets",
        "pub_link": "https://doi.org/10.48550/arXiv.2108.06232",
        "other_links": None,
    },
    "alpha_brass_nanoparticles": {
        "new_name": "alpha_brass_nanoparticles",
        "colabfit_id": "DS_cvf22oent5aj_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:94-aq",
        "pub_link": "https://doi.org/10.1021/acs.jpcc.1c02314",
        "other_links": ["http://doi.org/10.1021/acs.jpcc.0c00559"],
    },
    "ANI-Al_NC2021-train": {
        "new_name": "ANI-Al_NC2021_train",
        "colabfit_id": "DS_58756wvvjfen_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/atomistic-ml/ani-al",
        "pub_link": "https://doi.org/10.1038/s41467-021-21376-0",
        "other_links": None,
    },
    "ANI-Al_NC2021-test": {
        "new_name": "ANI-Al_NC2021_test",
        "colabfit_id": "DS_lm6b4vc6gdfn_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/atomistic-ml/ani-al",
        "pub_link": "https://doi.org/10.1038/s41467-021-21376-0",
        "other_links": None,
    },
    "Au-PBE-MSMSE-2021": {
        "new_name": "Au-PBE_MSMSE_2021",
        "colabfit_id": "DS_9qpwt7nxwbd0_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?name=Au-PBE&id=4&pageType=datasets",
        "pub_link": "https://doi.org/10.48550/arXiv.2108.06232",
        "other_links": None,
    },
    "C7H10O2": {
        "new_name": "C7H10O2",
        "colabfit_id": "DS_i5fgvjuup0h9_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.c.978904.v5",
        "pub_link": "https://doi.org/10.1038/sdata.2014.22",
        "other_links": None,
    },
    "C_Gardner_2022": {
        "new_name": "C_Gardner_2022",
        "colabfit_id": "DS_m9sb1m98e5jw_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/jla-gardner/carbon-data",
        "pub_link": "https://doi.org/10.48550/arXiv.2211.16443",
        "other_links": None,
    },
    "CA-9-BB-training": {
        "new_name": "CA-9_BB_training",
        "colabfit_id": "DS_y2h1podlwd81_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:6h-yj",
        "pub_link": "https://doi.org/10.1016/j.cartre.2021.100027",
        "other_links": None,
    },
    "CA-9-BB-validation": {
        "new_name": "CA-9_BB_validation",
        "colabfit_id": "DS_axgvf59hykr3_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:6h-yj",
        "pub_link": "https://doi.org/10.1016/j.cartre.2021.100027",
        "other_links": None,
    },
    "CA-9-RR-validation": {
        "new_name": "CA-9_RR_validation",
        "colabfit_id": "DS_ofo6c2027oyg_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:6h-yj",
        "pub_link": "https://doi.org/10.1016/j.cartre.2021.100027",
        "other_links": None,
    },
    "CA-9-RR-training": {
        "new_name": "CA-9_RR_training",
        "colabfit_id": "DS_2n8titcsowuj_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:6h-yj",
        "pub_link": "https://doi.org/10.1016/j.cartre.2021.100027",
        "other_links": None,
    },
    "CA-9-CA_9-training": {
        "new_name": "CA-9_training",
        "colabfit_id": "DS_k9d1ixct0yzv_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:6h-yj",
        "pub_link": "https://doi.org/10.1016/j.cartre.2021.100027",
        "other_links": None,
    },
    "CA-9-CA_9-validation": {
        "new_name": "CA-9_validation",
        "colabfit_id": "DS_6e68t5cggi26_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:6h-yj",
        "pub_link": "https://doi.org/10.1016/j.cartre.2021.100027",
        "other_links": None,
    },
    "CA-9-test": {
        "new_name": "CA-9_test",
        "colabfit_id": "DS_c83tj8qdb2nd_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:6h-yj",
        "pub_link": "https://doi.org/10.1016/j.cartre.2021.100027",
        "other_links": None,
    },
    "cG-SchNet": {
        "new_name": "cG-SchNet",
        "colabfit_id": "DS_bj8v98iazsm5_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/atomistic-machine-learning/cG-SchNet/",
        "pub_link": "https://doi.org/10.1038/s41467-022-28526-y",
        "other_links": None,
    },
    "COHInPt_schaaf_2023": {
        "new_name": "COHInPt_schaaf_2023",
        "colabfit_id": "DS_zyfigojpxdwe_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.5281/zenodo.8268726",
        "pub_link": "https://doi.org/10.48550/arXiv.2301.09931",
        "other_links": None,
    },
    "ComBat": {
        "new_name": "ComBat",
        "colabfit_id": "DS_tbpsmu8ee0cy_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/rashatwi/combat/",
        "pub_link": "https://doi.org/10.1038/s41598-022-20009-w",
        "other_links": None,
    },
    "Cu_FHIaims_NPJCM_2021": {
        "new_name": "Cu_FHIaims_NPJCM_2021",
        "colabfit_id": "DS_9ni8f0nskfk0_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.5281/zenodo.4734035",
        "pub_link": "https://doi.org/10.1038/s41524-021-00559-9",
        "other_links": None,
    },
    "DAS_ML-IP_CoSb_MgSb": {
        "new_name": "DAS_MLIP_CoSb_MgSb",
        "colabfit_id": "DS_7hfawqjxg9sq_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1103/PhysRevB.104.094310",
        "pub_link": "https://doi.org/10.1103/PhysRevB.104.094310",
        "other_links": None,
    },
    "DeePMD-SE": {
        "new_name": "DeePMD_SE",
        "colabfit_id": "DS_kotuk00qiuog_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?name=deepmd-se-dataset&id=63&pageType=datasets",
        "pub_link": "https://doi.org/10.48550/arXiv.1805.09003",
        "other_links": None,
    },
    "DFT_polymorphs_PNAS_2022_PBE_TS_benzene_test": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE_TS_benzene_test",
        "colabfit_id": "DS_y3uemf2bc4b0_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE_TS_benzene_train": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE_TS_benzene_train",
        "colabfit_id": "DS_5b3nfyh0zen8_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE_TS_benzene_validation": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE_TS_benzene_validation",
        "colabfit_id": "DS_d7htf12f2827_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE_TS_glycine_test": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE_TS_glycine_test",
        "colabfit_id": "DS_cr86ofn5k5gk_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE_TS_glycine_train": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE_TS_glycine_train",
        "colabfit_id": "DS_nob3pt0ka2j2_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE_TS_glycine_validation": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE_TS_glycine_validation",
        "colabfit_id": "DS_k4t7iqimbjn2_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE_TS_succinic_acid_test": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE_TS_succinic_acid_test",
        "colabfit_id": "DS_cyf3gwuavbiy_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE_TS_succinic_acid_train": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE_TS_succinic_acid_train",
        "colabfit_id": "DS_66cz98nuftk0_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE_TS_succinic_acid_validation": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE_TS_succinic_acid_validation",
        "colabfit_id": "DS_hahu7ma0m3o0_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE0_MBD_benzene_test": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE0_MBD_benzene_test",
        "colabfit_id": "DS_xk19rszuj46f_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE0_MBD_benzene_train": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE0_MBD_benzene_train",
        "colabfit_id": "DS_ox9uuun3mzav_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE0_MBD_benzene_validation": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE0_MBD_benzene_validation",
        "colabfit_id": "DS_sg0xakfft1cj_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE0_MBD_glycine_test": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE0_MBD_glycine_test",
        "colabfit_id": "DS_e4zsfn53o9us_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE0_MBD_glycine_train": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE0_MBD_glycine_train",
        "colabfit_id": "DS_uk72hlukj3pf_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE0_MBD_glycine_validation": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE0_MBD_glycine_validation",
        "colabfit_id": "DS_y0er5pzso3t9_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE0_MBD_succinic_acid_test": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE0_MBD_succinic_acid_test",
        "colabfit_id": "DS_doc6jfrngxsd_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE0_MBD_succinic_acid_train": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE0_MBD_succinic_acid_train",
        "colabfit_id": "DS_qu5881ts5mqn_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DFT_polymorphs_PNAS_2022_PBE0_MBD_succinic_acid_validation": {
        "new_name": "DFT_polymorphs_PNAS_2022_PBE0_MBD_succinic_acid_validation",
        "colabfit_id": "DS_atw4j47wpz5x_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:vp-jf",
        "pub_link": "https://doi.org/10.1073/pnas.2111769119",
        "other_links": [
            "https://github.com/venkatkapil24/data_molecular_fluctuations",
        ],
    },
    "DP-GEN-Cu": {
        "new_name": "DP-GEN_Cu",
        "colabfit_id": "DS_i5npcz713468_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?name=Cu-dpgen&id=16&pageType=datasets",
        "pub_link": "https://doi.org/10.1016/j.cpc.2020.107206",
        "other_links": None,
    },
    "FitSNAP-Fe-NPJ-2021": {
        "new_name": "FitSNAP_Fe_NPJ_2021",
        "colabfit_id": "DS_taxhgs1dgvnf_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/FitSNAP",
        "pub_link": "https://doi.org/10.1038/s41524-021-00617-2",
        "other_links": None,
    },
    "Forces-are-not-Enough": {
        "new_name": "Forces_are_not_Enough",
        "colabfit_id": "DS_u0iyfmbjyjrq_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.5281/zenodo.7196578",
        "pub_link": "https://doi.org/10.48550/arXiv.2210.07237",
        "other_links": [
            "https://github.com/kyonofx/MDsim/",
        ],
    },
    "GDB_9_nature_2014": {
        "new_name": "GDB_9_nature_2014",
        "colabfit_id": "DS_p2a29dcutz7z_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.c.978904.v5",
        "pub_link": "https://doi.org/10.1038/sdata.2014.22",
        "other_links": None,
    },
    "GFN-xTB_jcim_2021": {
        "new_name": "GFN_xTB_jcim_2021",
        "colabfit_id": "DS_of9zwkoyy3rv_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:14-4m",
        "pub_link": "https://doi.org/10.1021/acs.jcim.1c01170",
        "other_links": None,
    },
    "HDNNP-H2O": {
        "new_name": "HDNNP_H2O",
        "colabfit_id": "DS_ovtilltolpq3_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.5281/zenodo.2634097",
        "pub_link": "https://doi.org/10.1103/PhysRevLett.98.146401",
        "other_links": [
            "https://doi.org/10.1073/pnas.1602375113",
        ],
    },
    "HfO2-DPGEN-PRB-2021": {
        "new_name": "HfO2_DPGEN_PRB_2021",
        "colabfit_id": "DS_klj8wt21p021_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?pageType=datasets&name=HfO2-dpgen",
        "pub_link": "https://doi.org/10.1103/PhysRevB.103.024108",
        "other_links": None,
    },
    "HfO2_NPJ_2020": {
        "new_name": "HfO2_NPJ_2020",
        "colabfit_id": "DS_tgmqhupk5ouv_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/argonne-lcf/active-learning-md",
        "pub_link": "https://doi.org/10.1038/s41524-020-00367-7",
        "other_links": None,
    },
    "HME21_test": {
        "new_name": "HME21_test",
        "colabfit_id": "DS_6by90fc9cv54_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.19658538.v2",
        "pub_link": "https://doi.org/10.1038/s41467-022-30687-9",
        "other_links": None,
    },
    "HME21_train": {
        "new_name": "HME21_train",
        "colabfit_id": "DS_49yxirzaac30_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.19658538.v2",
        "pub_link": "https://doi.org/10.1038/s41467-022-30687-9",
        "other_links": None,
    },
    "HME21_validation": {
        "new_name": "HME21_validation",
        "colabfit_id": "DS_xhuj63gted7u_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.19658538.v2",
        "pub_link": "https://doi.org/10.1038/s41467-022-30687-9",
        "other_links": None,
    },
    "H_nature_2022": {
        "new_name": "H_nature_2022",
        "colabfit_id": "DS_p6tlx3dllrqz_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.19601689.v3",
        "pub_link": "https://doi.org/10.1038/s41597-022-01330-5",
        "other_links": None,
    },
    "HO-LiMoNiTi-NPJCM-2020-LiMoNiTi-train": {
        "new_name": "HO_LiMoNiTi_NPJCM_2020_LiMoNiTi_train",
        "colabfit_id": "DS_dafx0ntmukp6_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:2020.0037/v1",
        "pub_link": "https://doi.org/10.1038/s41524-020-0323-8",
        "other_links": None,
    },
    "HO-LiMoNiTi-NPJCM-2020-LiMoNiTi-validation": {
        "new_name": "HO_LiMoNiTi_NPJCM_2020_LiMoNiTi_validation",
        "colabfit_id": "DS_ma7zdmiwqglh_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:2020.0037/v1",
        "pub_link": "https://doi.org/10.1038/s41524-020-0323-8",
        "other_links": None,
    },
    "HO-LiMoNiTi-NPJCM-2020-bulk-water-train-test": {
        "new_name": "HO_LiMoNiTi_NPJCM_2020_bulk_water_train_test",
        "colabfit_id": "DS_o9740kr8ojom_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:2020.0037/v1",
        "pub_link": "https://doi.org/10.1038/s41524-020-0323-8",
        "other_links": None,
    },
    "HO-LiMoNiTi-NPJCM-2020-bulk-water-validation": {
        "new_name": "HO_LiMoNiTi_NPJCM_2020_bulk_water_validation",
        "colabfit_id": "DS_47lrcubrsnw1_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:2020.0037/v1",
        "pub_link": "https://doi.org/10.1038/s41524-020-0323-8",
        "other_links": None,
    },
    "HO-LiMoNiTi-NPJCM-2020-water-clusters": {
        "new_name": "HO_LiMoNiTi_NPJCM_2020_water_clusters",
        "colabfit_id": "DS_ppomglveyhbu_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:2020.0037/v1",
        "pub_link": "https://doi.org/10.1038/s41524-020-0323-8",
        "other_links": None,
    },
    "HO_pnas_2019": {
        "new_name": "HO_pnas_2019",
        "colabfit_id": "DS_x2fruhd0d3ne_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://archive.materialscloud.org/record/2018.0020/v1",
        "pub_link": "https://doi.org/10.1073/pnas.1815117116",
        "other_links": None,
    },
    "HPt_nc_2022": {
        "new_name": "HPt_NC_2022",
        "colabfit_id": "DS_vjkwrlav3rcd_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:r0-84",
        "pub_link": "https://doi.org/10.1038/s41467-022-32294-0",
        "other_links": None,
    },
    "In2Se3-2D-DPGEN": {
        "new_name": "In2Se3_2D_DPGEN",
        "colabfit_id": "DS_xr60k3hjtnd6_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?pageType=datasets&name=In2Se3-2D-dpgen",
        "pub_link": "https://doi.org/10.1103/PhysRevB.104.174107",
        "other_links": None,
    },
    "ISO17_NC_2017": {
        "new_name": "ISO17_NC_2017",
        "colabfit_id": "DS_tyi807beniwx_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://quantum-machine.org/datasets/",
        "pub_link": "https://proceedings.neurips.cc/paper/2017/hash/303ed4c69846ab36c2904d3ba8573050-Abstract.html",
        "other_links": [
            "https://doi.org/10.1038/s41467-019-12875-2",
            "https://doi.org/10.1038/ncomms13890",
            "https://doi.org/10.1038/sdata.2014.22",
        ],
    },
    "LiGePS-SSE-PBE": {
        "new_name": "LiGePS_SSE_PBE",
        "colabfit_id": "DS_obhx3e6j1z3b_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?pageType=datasets&name=LiGePS-SSE-PBE",
        "pub_link": "https://doi.org/10.1063/5.0041849",
        "other_links": None,
    },
    "LiGePS-SSE-PBEsol": {
        "new_name": "LiGePS_SSE_PBEsol",
        "colabfit_id": "DS_ha9ilqx07mw1_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?pageType=datasets&name=LiGePS-SSE-PBEsol",
        "pub_link": "https://doi.org/10.1063/5.0041849",
        "other_links": None,
    },
    "LiSiPS-SSE-PBE": {
        "new_name": "LiSiPS_SSE_PBE",
        "colabfit_id": "DS_6jinoiixazcj_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?pageType=datasets&name=LiSiPS-SSE-PBE",
        "pub_link": "https://doi.org/10.1063/5.0041849",
        "other_links": None,
    },
    "LiSiPS-SSE-PBEsol": {
        "new_name": "LiSiPS_SSE_PBEsol",
        "colabfit_id": "DS_l7vzn4i39uyb_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?pageType=datasets&name=LiSiPS-SSE-PBEsol",
        "pub_link": "https://doi.org/10.1063/5.0041849",
        "other_links": None,
    },
    "mbGDML_maldonado_2023": {
        "new_name": "mbGDML_maldonado_2023",
        "colabfit_id": "DS_cz3fqphrrlr6_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.5281/zenodo.7112197",
        "pub_link": "https://doi.org/10.26434/chemrxiv-2023-wdd1r",
        "other_links": None,
    },
    "Mg_edmonds_2022": {
        "new_name": "Mg_edmonds_2022",
        "colabfit_id": "DS_3ldikbbjxirh_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.17617/3.A3MB7Z",
        "pub_link": "https://doi.org/10.1103/PhysRevB.107.104103",
        "other_links": [
            "https://github.com/eisenforschung/magnesium-mtp-training-data",
            "https://arxiv.org/abs/2207.04009",
        ],
    },
    "MISPR": {
        "new_name": "MISPR",
        "colabfit_id": "DS_sq9lx2ya2zsh_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/rashatwi/mispr-dataset",
        "pub_link": "https://doi.org/10.1038/s41598-022-20009-w",
        "other_links": None,
    },
    "NDSC_TUT_2022": {
        "new_name": "NDSC_TUT_2022",
        "colabfit_id": "DS_bkem3c256w5x_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/ConnorSA/ndsc_tut",
        "pub_link": "https://doi.org/10.48550/arXiv.2207.11828",
        "other_links": None,
    },
    "NEP_PRB_2021": {
        "new_name": "NEP_PRB_2021",
        "colabfit_id": "DS_9ngg9wkdp48u_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.5281/zenodo.5109599",
        "pub_link": "https://doi.org/10.1103/PhysRevB.104.104309",
        "other_links": None,
    },
    "NEP-qHPF-test": {
        "new_name": "NEP_qHPF_test",
        "colabfit_id": "DS_xu34yu1d1oxk_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.5281/zenodo.7018572",
        "pub_link": "https://doi.org/10.1016/j.eml.2022.101929",
        "other_links": None,
    },
    "NEP-qHPF-train": {
        "new_name": "NEP_qHPF_train",
        "colabfit_id": "DS_fydj6ftcvdxm_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.5281/zenodo.7018572",
        "pub_link": "https://doi.org/10.1016/j.eml.2022.101929",
        "other_links": None,
    },
    "NequIP-NC-2022": {
        "new_name": "NequIP_NC_2022",
        "colabfit_id": "DS_sipksdvyrxsf_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:s0-5n",
        "pub_link": "https://doi.org/10.1038/s41467-022-29939-5",
        "other_links": None,
    },
    "NNIP_FeH_PRM_2021": {
        "new_name": "NNIP_FeH_PRM_2021",
        "colabfit_id": "DS_pjk3hbs3bpn0_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/mengfsou/NNIP-FeH",
        "pub_link": "https://doi.org/10.1103/PhysRevMaterials.5.113606",
        "other_links": None,
    },
    "NNP-Ga2O3": {
        "new_name": "NNP_Ga2O3",
        "colabfit_id": "DS_c2b2hbe0so7b_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/RuiyangLi6/NNP_Ga2O3",
        "pub_link": "https://doi.org/10.1063/5.0025051",
        "other_links": None,
    },
    "NVNMD-GeTe": {
        "new_name": "NVNMD_GeTe",
        "colabfit_id": "DS_qvxzb2z6j528_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/LiuGroupHNU/nvnmd",
        "pub_link": "https://doi.org/10.1038/s41524-022-00773-z",
        "other_links": None,
    },
    "QM7b_AlphaML": {
        "new_name": "QM7b_AlphaML",
        "colabfit_id": "DS_t4fu56ekhrcu_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:2019.0002/v3",
        "pub_link": "https://doi.org/10.1038/s41597-019-0157-8",
        "other_links": ["http://doi.org/10.1073/pnas.1816132116"],
    },
    "QM-22": {
        "new_name": "QM_22",
        "colabfit_id": "DS_qtjh8l700994_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/jmbowma/QM-22",
        "pub_link": "https://doi.org/10.1063/5.0089200",
        "other_links": None,
    },
    "QM_hamiltonian_nature_2019": {
        "new_name": "QM_hamiltonian_nature_2019",
        "colabfit_id": "DS_1g1opovu29qj_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://quantum-machine.org/datasets/",
        "pub_link": "https://doi.org/10.1038/s41467-019-12875-2",
        "other_links": None,
    },
    "REANN_CO2_Ni100": {
        "new_name": "REANN_CO2_Ni100",
        "colabfit_id": "DS_vso98nin62ed_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/zhangylch/REANN",
        "pub_link": "https://doi.org/10.1021/acs.jpclett.9b00085",
        "other_links": [
            "https://doi.org/10.1103/PhysRevLett.127.156002",
            "https://doi.org/10.1063/5.0080766",
        ],
    },
    "rMD17": {
        "new_name": "rMD17",
        "colabfit_id": "DS_3znoidgiaz6o_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.12672038.v3",
        "pub_link": "https://doi.org/10.48550/arXiv.2007.09593",
        "other_links": None,
    },
    "Si-H-GAP-reference": {
        "new_name": "Si-H-GAP_reference",
        "colabfit_id": "DS_ef6n0z8no4y0_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/dgunruh/Si-H-GAP",
        "pub_link": "https://doi.org/10.1103/PhysRevMaterials.6.065603",
        "other_links": None,
    },
    "Si-H-GAP-training": {
        "new_name": "Si-H-GAP_training",
        "colabfit_id": "DS_jp7xwcv8bala_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/dgunruh/Si-H-GAP",
        "pub_link": "https://doi.org/10.1103/PhysRevMaterials.6.065603",
        "other_links": None,
    },
    "Si-H-GAP-validation": {
        "new_name": "Si-H-GAP_validation",
        "colabfit_id": "DS_szmo638f3l7c_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/dgunruh/Si-H-GAP",
        "pub_link": "https://doi.org/10.1103/PhysRevMaterials.6.065603",
        "other_links": None,
    },
    "SIMPLE_NN_SiO2": {
        "new_name": "SIMPLE_NN_SiO2",
        "colabfit_id": "DS_hc3x9jj4j3fp_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.17632/pjv2yr7pvr.1",
        "pub_link": "https://doi.org/10.1016/j.cpc.2019.04.014",
        "other_links": None,
    },
    "Sn-SCAN-PRM-2023": {
        "new_name": "Sn_SCAN_PRM_2023",
        "colabfit_id": "DS_odv7d6cuwsjg_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?pageType=datasets&name=Sn-SCAN",
        "pub_link": "https://doi.org/10.1103/PhysRevMaterials.7.053603",
        "other_links": None,
    },
    "TdS-PdV_Atari5200": {
        "new_name": "TdS_PdV_Atari5200",
        "colabfit_id": "DS_tuta6s1w10vm_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.5281/zenodo.7278341",
        "pub_link": "https://doi.org/10.1021/acs.jpclett.2c03445",
        "other_links": [
            "https://github.com/saidigroup/Metal-Oxide-Dataset/tree/v1.0",
        ],
    },
    "Ti-NPJCM-2021": {
        "new_name": "Ti_NPJCM_2021",
        "colabfit_id": "DS_87r90ch9h5k7_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.aissquare.com/datasets/detail?pageType=datasets&name=Ti",
        "pub_link": "https://doi.org/10.1038/s41524-021-00661-y",
        "other_links": None,
    },
    "TSFF_PLOS_2022": {
        "new_name": "TSFF_PLOS_2022",
        "colabfit_id": "DS_zymntzfb6w2h_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1371/journal.pone.0264960.s001",
        "pub_link": "https://doi.org/10.1371/journal.pone.0264960",
        "other_links": None,
    },
    "Zeo-1_SD_2022": {
        "new_name": "Zeo_1_SD_2022",
        "colabfit_id": "DS_lqbm3jy2t7cf_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.24435/materialscloud:cv-zd",
        "pub_link": "https://doi.org/10.1038/s41597-022-01160-5",
        "other_links": None,
    },
    "ABC2D6-16_PRL2018": {
        "new_name": "ABC2D6_16_PRL2018",
        "colabfit_id": "DS_o6ll3w7kjo21_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://qmml.org/datasets.html",
        "pub_link": "https://doi.org/10.1103/PhysRevLett.117.135502",
        "other_links": None,
    },
    "BOTnetACAC_arXiv2022-isolated": {
        "new_name": "BOTnetACAC_2022_isolated",
        "colabfit_id": "DS_5nhvii00o08o_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/davkovacs/BOTNet-datasets",
        "pub_link": "https://doi.org/10.48550/arXiv.2205.06643",
        "other_links": None,
    },
    "BOTnetACAC_arXiv2022-H_transfer": {
        "new_name": "BOTnetACAC_2022_H_transfer",
        "colabfit_id": "DS_fwxvcjshduj4_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/davkovacs/BOTNet-datasets",
        "pub_link": "https://doi.org/10.48550/arXiv.2205.06643",
        "other_links": None,
    },
    "BOTnetACAC_arXiv2022-test_300K_MD": {
        "new_name": "BOTnetACAC_2022_test_300K_MD",
        "colabfit_id": "DS_81102v45w9qv_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/davkovacs/BOTNet-datasets",
        "pub_link": "https://doi.org/10.48550/arXiv.2205.06643",
        "other_links": None,
    },
    "BOTnetACAC_arXiv2022-test_600K_MD": {
        "new_name": "BOTnetACAC_2022_test_600K_MD",
        "colabfit_id": "DS_ma1lggm10pry_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/davkovacs/BOTNet-datasets",
        "pub_link": "https://doi.org/10.48550/arXiv.2205.06643",
        "other_links": None,
    },
    "BOTnetACAC_arXiv2022-Dihedral_scan": {
        "new_name": "BOTnetACAC_2022_Dihedral_scan",
        "colabfit_id": "DS_lxbuk7fgav22_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/davkovacs/BOTNet-datasets",
        "pub_link": "https://doi.org/10.48550/arXiv.2205.06643",
        "other_links": None,
    },
    "BOTnetACAC_arXiv2022-train_300K_MD": {
        "new_name": "BOTnetACAC_2022_train_300K_MD",
        "colabfit_id": "DS_l5w4lwupwcbp_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/davkovacs/BOTNet-datasets",
        "pub_link": "https://doi.org/10.48550/arXiv.2205.06643",
        "other_links": None,
    },
    "BOTnetACAC_arXiv2022-train_600K_MD": {
        "new_name": "BOTnetACAC_2022_train_600K_MD",
        "colabfit_id": "DS_1kzqigdwj1lg_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/davkovacs/BOTNet-datasets",
        "pub_link": "https://doi.org/10.48550/arXiv.2205.06643",
        "other_links": None,
    },
    "AgPd_npj2021": {
        "new_name": "AgPd_NPJ_2021",
        "colabfit_id": "DS_7wyhcjvg1cqm_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/msg-byu/agpd",
        "pub_link": "https://doi.org/10.1038/s41524-020-00477-2",
        "other_links": None,
    },
    "AlNiCu_AIP2020": {
        "new_name": "AlNiCu_AIP_2020",
        "colabfit_id": "DS_6x81ekmio3j7_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/DescriptorZoo/sensitivity-dimensionality-results",
        "pub_link": "https://doi.org/10.1063/5.0016005",
        "other_links": None,
    },
    "AlNiTi_CMS2019": {
        "new_name": "AlNiTi_CMS_2019",
        "colabfit_id": "DS_e3j52tou8y7a_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://gitlab.com/kgubaev/accelerating-high-throughput-searches-for-new-alloys-with-active-learning-data",
        "pub_link": "https://doi.org/10.1016/j.commatsci.2018.09.031",
        "other_links": None,
    },
    "Aspirin_ccsd_NC2018-train": {
        "new_name": "Aspirin_ccsd_NC2018_train",
        "colabfit_id": "DS_v7g5wk8twfkd_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1038/s41467-018-06169-2",
        "other_links": None,
    },
    "Aspirin_ccsd_NC2018-test": {
        "new_name": "Aspirin_ccsd_NC2018_test",
        "colabfit_id": "DS_24kdsvpuo4id_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1038/s41467-018-06169-2",
        "other_links": None,
    },
    "BA10-18": {
        "new_name": "BA10_18",
        "colabfit_id": "DS_uysozdxiio8s_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://qmml.org/datasets.html",
        "pub_link": "https://doi.org/10.1038/s41524-019-0189-9",
        "other_links": None,
    },
    "Benzene_ccsdt_NC2018-train": {
        "new_name": "Benzene_ccsdt_NC2018_train",
        "colabfit_id": "DS_4joqarq8zvkw_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1038/s41467-018-06169-2",
        "other_links": None,
    },
    "Benzene_ccsdt_NC2018-test": {
        "new_name": "Benzene_ccsdt_NC2018_test",
        "colabfit_id": "DS_tkwrj6gu7p7y_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1038/s41467-018-06169-2",
        "other_links": None,
    },
    "Benzene_DFT_NC2018": {
        "new_name": "Benzene_DFT_NC2018",
        "colabfit_id": "DS_lior95sde6v8_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1126/sciadv.1603015",
        "other_links": [
            "https://doi.org/10.1038/s41467-018-06169-2",
        ],
    },
    "C_npj2020": {
        "new_name": "C_npj2020",
        "colabfit_id": "DS_07sxaqcpzqz7_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.12649811.v1",
        "pub_link": "https://doi.org/10.1038/s41524-020-00390-8",
        "other_links": None,
    },
    "Carbon_GAP_JCP2020": {
        "new_name": "Carbon_GAP_JCP2020",
        "colabfit_id": "DS_r4w09ja1k41s_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://www.repository.cam.ac.uk/handle/1810/307452",
        "pub_link": "https://doi.org/10.1063/5.0005084",
        "other_links": None,
    },
    "CHON_JCP2020": {
        "new_name": "CHON_JCP2020",
        "colabfit_id": "DS_etl5q6pseift_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/DescriptorZoo/sensitivity-dimensionality-results/tree/master/datasets",
        "pub_link": "https://doi.org/10.1063/5.0016005",
        "other_links": None,
    },
    "CoNbV_CMS2019": {
        "new_name": "CoNbV_CMS2019",
        "colabfit_id": "DS_visyvn84h78m_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://gitlab.com/kgubaev/accelerating-high-throughput-searches-for-new-alloys-with-active-learning-data",
        "pub_link": "https://doi.org/10.1016/j.commatsci.2018.09.031",
        "other_links": None,
    },
    "CuPd_CMS2019": {
        "new_name": "CuPd_CMS2019",
        "colabfit_id": "DS_cl7gekygi1qw_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://gitlab.com/kgubaev/accelerating-high-throughput-searches-for-new-alloys-with-active-learning-data",
        "pub_link": "https://doi.org/10.1016/j.commatsci.2018.09.031",
        "other_links": None,
    },
    "Ethanol_ccsdt_NC2018-train": {
        "new_name": "Ethanol_ccsdt_NC2018_train",
        "colabfit_id": "DS_4gdp58afs9h3_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1038/s41467-018-06169-2",
        "other_links": None,
    },
    "Ethanol_ccsdt_NC2018-test": {
        "new_name": "Ethanol_ccsdt_NC2018_test",
        "colabfit_id": "DS_iazxrfhluscp_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1038/s41467-018-06169-2",
        "other_links": None,
    },
    "InP_JPCA2020": {
        "new_name": "InP_JPCA2020",
        "colabfit_id": "DS_11ogp04ec92p_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/FitSNAP/FitSNAP/tree/master/examples/InP_JPCA2020",
        "pub_link": "https://doi.org/10.1021/acs.jpca.0c02450",
        "other_links": None,
    },
    "Malonaldehyde_ccsdt_NC2018-train": {
        "new_name": "Malonaldehyde_ccsdt_NC2018_train",
        "colabfit_id": "DS_ka9oer9rjlma_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1038/s41467-018-06169-2",
        "other_links": None,
    },
    "Malonaldehyde_ccsdt_NC2018-test": {
        "new_name": "Malonaldehyde_ccsdt_NC2018_test",
        "colabfit_id": "DS_37kakgn0rux8_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1038/s41467-018-06169-2",
        "other_links": None,
    },
    "mlearn_Cu_test": {
        "new_name": "mlearn_Cu_test",
        "colabfit_id": "DS_vthcw3izvtg8_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "MD22_Ac_Ala3_NHMe": {
        "new_name": "MD22_Ac_Ala3_NHMe",
        "colabfit_id": "DS_0u7wyw92ssrd_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1126/sciadv.adf0873",
        "other_links": None,
    },
    "MD22_AT_AT_CG_CG": {
        "new_name": "MD22_AT_AT_CG_CG",
        "colabfit_id": "DS_ki2f19l3emx1_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1126/sciadv.adf0873",
        "other_links": None,
    },
    "MD22_AT_AT": {
        "new_name": "MD22_AT_AT",
        "colabfit_id": "DS_bialb36a6hrh_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1126/sciadv.adf0873",
        "other_links": None,
    },
    "MD22_buckyball_catcher": {
        "new_name": "MD22_buckyball_catcher",
        "colabfit_id": "DS_hld8h5hqrqbp_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1126/sciadv.adf0873",
        "other_links": None,
    },
    "MD22_DHA": {
        "new_name": "MD22_DHA",
        "colabfit_id": "DS_hssbbnv4wp9a_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1126/sciadv.adf0873",
        "other_links": None,
    },
    "MD22_double_walled_nanotube": {
        "new_name": "MD22_double_walled_nanotube",
        "colabfit_id": "DS_knoatqdsnpoh_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1126/sciadv.adf0873",
        "other_links": None,
    },
    "MD22_stachyose": {
        "new_name": "MD22_stachyose",
        "colabfit_id": "DS_4144akr5iyup_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1126/sciadv.adf0873",
        "other_links": None,
    },
    "mlearn_Ge_test": {
        "new_name": "mlearn_Ge_test",
        "colabfit_id": "DS_wmj0lbhn2nob_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "mlearn_Li_test": {
        "new_name": "mlearn_Li_test",
        "colabfit_id": "DS_7xt39upviipp_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "mlearn_Mo_test": {
        "new_name": "mlearn_Mo_test",
        "colabfit_id": "DS_qgzddjz0td6s_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "mlearn_Ni_test": {
        "new_name": "mlearn_Ni_test",
        "colabfit_id": "DS_93nvj3h7vt4e_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "mlearn_Si_test": {
        "new_name": "mlearn_Si_test",
        "colabfit_id": "DS_97i1u7v70s1e_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "mlearn_Cu_train": {
        "new_name": "mlearn_Cu_train",
        "colabfit_id": "DS_7zclo2vfrzze_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "mlearn_Ge_train": {
        "new_name": "mlearn_Ge_train",
        "colabfit_id": "DS_vp2paxctz7f8_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "mlearn_Li_train": {
        "new_name": "mlearn_Li_train",
        "colabfit_id": "DS_5c9xknoouzof_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "mlearn_Mo_train": {
        "new_name": "mlearn_Mo_train",
        "colabfit_id": "DS_ppmaukeeyjct_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "mlearn_Ni_train": {
        "new_name": "mlearn_Ni_train",
        "colabfit_id": "DS_p0t392lmfll6_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "mlearn_Si_train": {
        "new_name": "mlearn_Si_train",
        "colabfit_id": "DS_aqo7zlicjgcq_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/materialsvirtuallab/mlearn",
        "pub_link": "https://doi.org/10.1021/acs.jpca.9b08723",
        "other_links": None,
    },
    "Mo_PRM2019": {
        "new_name": "Mo_PRM2019",
        "colabfit_id": "DS_hhlicrd553vj_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://gitlab.com/acclab/gap-data/-/tree/master/Mo",
        "pub_link": "https://doi.org/10.1103/PhysRevMaterials.4.093802",
        "other_links": None,
    },
    "MoNbTaVW_PRB2021": {
        "new_name": "MoNbTaVW_PRB2021",
        "colabfit_id": "DS_2xckg5q43m0a_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.23729/1b845398-5291-4447-b417-1345acdd2eae",
        "pub_link": "https://doi.org/10.1103/PhysRevB.104.104101",
        "other_links": None,
    },
    "Nb_PRM2019": {
        "new_name": "Nb_PRM2019",
        "colabfit_id": "DS_448x8b1vj02p_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://gitlab.com/acclab/gap-data/-/tree/master/",
        "pub_link": "https://doi.org/10.1103/PhysRevMaterials.4.093802",
        "other_links": None,
    },
    "NMD-18": {
        "new_name": "NMD_18",
        "colabfit_id": "DS_6aj37o1t68bx_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://qmml.org/datasets.html",
        "pub_link": "https://doi.org/10.1038/s41524-019-0239-3",
        "other_links": None,
    },
    "PtNi_alloy_NPJ2022": {
        "new_name": "PtNi_alloy_NPJ2022",
        "colabfit_id": "DS_q3tqbvytfk6e_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://zenodo.org/record/5645281#.Y2CPkeTMJEa",
        "pub_link": "https://doi.org/10.1038/s41524-022-00807-6",
        "other_links": None,
    },
    "QM9x": {
        "new_name": "QM9x",
        "colabfit_id": "DS_xucp4zl589wx_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.20449701.v2",
        "pub_link": "https://doi.org/10.1038/s41597-022-01870-w",
        "other_links": None,
    },
    "Si_PRX_GAP": {
        "new_name": "Si_PRX_GAP",
        "colabfit_id": "DS_y23xph41frx2_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.17863/CAM.65004",
        "pub_link": "https://doi.org/10.1103/PhysRevX.8.041048",
        "other_links": None,
    },
    "Ta_Linear_JCP2015": {
        "new_name": "Ta_Linear_JCP2014",
        "colabfit_id": "DS_zc8ca32nd45o_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/FitSNAP/FitSNAP/tree/master/examples/Ta_Linear_JCP2014",
        "pub_link": "https://doi.org/10.1016/j.jcp.2014.12.018",
        "other_links": None,
    },
    "Ta_PINN_2021": {
        "new_name": "Ta_PINN_2021",
        "colabfit_id": "DS_h6m37bkwsc97_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": "https://doi.org/10.1016/j.commatsci.2021.111180",
        "other_links": None,
    },
    "Ta_PRM2019": {
        "new_name": "Ta_PRM2019",
        "colabfit_id": "DS_f897om5zgwj4_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://gitlab.com/acclab/gap-data/-/tree/master",
        "pub_link": "https://doi.org/10.1103/PhysRevMaterials.4.093802",
        "other_links": None,
    },
    "TiMoS_alloys_CMS2021": {
        "new_name": "TiMoS_alloys_CMS2021",
        "colabfit_id": "DS_xp7owpcgkumn_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://eprints.soton.ac.uk/443461/",
        "pub_link": "https://doi.org/10.1016/j.commatsci.2020.110044",
        "other_links": None,
    },
    "TiO2_CMS2016": {
        "new_name": "TiO2_CMS2016",
        "colabfit_id": "DS_hroevontx5o1_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/DescriptorZoo/sensitivity-dimensionality-results/tree/master/datasets/TiO2",
        "pub_link": "https://doi.org/10.1016/j.commatsci.2015.11.047",
        "other_links": None,
    },
    "TiZrHfTa_APS2021": {
        "new_name": "TiZrHfTa_APS2021",
        "colabfit_id": "DS_ves6w5s1957e_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": "https://doi.org/10.1103/PhysRevMaterials.5.073801",
        "other_links": None,
    },
    "Toluene_ccsdt_NC2018-train": {
        "new_name": "Toluene_ccsdt_NC2018_train",
        "colabfit_id": "DS_nvr2dj009uce_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1038/s41467-018-06169-2",
        "other_links": None,
    },
    "Toluene_ccsdt_NC2018-test": {
        "new_name": "Toluene_ccsdt_NC2018_test",
        "colabfit_id": "DS_s3v10vkwcx5c_0",
        "incar": None,
        "outcar": None,
        "data_link": "http://sgdml.org/",
        "pub_link": "https://doi.org/10.1038/s41467-018-06169-2",
        "other_links": None,
    },
    "V_PRM2019": {
        "new_name": "V_PRM2019",
        "colabfit_id": "DS_y2rh9kazvoxx_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://gitlab.com/acclab/gap-data/-/tree/master",
        "pub_link": "https://doi.org/10.1103/PhysRevMaterials.4.093802",
        "other_links": None,
    },
    "W-14": {
        "new_name": "W_14",
        "colabfit_id": "DS_inesgduyzjeb_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://qmml.org/datasets.html",
        "pub_link": "https://doi.org/10.1103/PhysRevB.90.104108",
        "other_links": None,
    },
    "W_PRB2019": {
        "new_name": "W_PRB2019",
        "colabfit_id": "DS_rfff2v7i1cqu_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://gitlab.com/acclab/gap-data/-/tree/master/W/2019-05-24",
        "pub_link": "https://doi.org/10.1103/PhysRevB.100.144105",
        "other_links": None,
    },
    "WBe_PRB2019": {
        "new_name": "WBe_PRB2019",
        "colabfit_id": "DS_o5slgmgc5wqg_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://github.com/FitSNAP/FitSNAP/tree/master/examples/WBe_PRB2019",
        "pub_link": "https://doi.org/10.1103/PhysRevB.99.184305",
        "other_links": None,
    },
    ######
    ##########
    "COLL-test": {
        "new_name": "COLL_test",
        "colabfit_id": "DS_gnuwdf4eo4wh_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.13289165.v1",
        "pub_link": "https://doi.org/10.48550/arXiv.2011.14115",
        "other_links": None,
    },
    "COLL-train": {
        "new_name": "COLL_train",
        "colabfit_id": "DS_ehn9uyzrwmno_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.13289165.v1",
        "pub_link": "https://doi.org/10.48550/arXiv.2011.14115",
        "other_links": None,
    },
    "COLL-validation": {
        "new_name": "COLL_validation",
        "colabfit_id": "DS_wazd3rw5ck77_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.6084/m9.figshare.13289165.v1",
        "pub_link": "https://doi.org/10.48550/arXiv.2011.14115",
        "other_links": None,
    },
    "WS22": {
        "new_name": "WS22",
        "colabfit_id": "DS_lvpu4w3b4hf2_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.5281/zenodo.7032333",
        "pub_link": "https://doi.org/10.1038/s41597-023-01998-3",
        "other_links": None,
    },
    "NENCI-2021": {
        "new_name": "NENCI_2021",
        "colabfit_id": "DS_23uztknncdd6_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1063/5.0068862",
        "pub_link": "https://doi.org/10.1063/5.0068862",
        "other_links": None,
    },
    "flexible_molecules_JCP2021": {
        "new_name": "flexible_molecules_JCP2021",
        "colabfit_id": "DS_5r65ut98mmmn_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1063/5.0038516",
        "pub_link": "https://doi.org/10.1063/5.0038516",
        "other_links": None,
    },
    
    "Si_JCP_2017": {
        "new_name": "Si_JCP_2017",
        "colabfit_id": "DS_44auexrg3lsd_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.1063/1.4990503",
        "pub_link": "https://doi.org/10.1063/1.4990503",
        "other_links": None,
    },
    # duplicate
    # "Si_PRX_2018": {
    #     "new_name": "Si_PRX_2018",
    #     "colabfit_id": "DS_dfnargd6yu0c_0",
    #     "incar": None,
    #     "outcar": None,
    #     "data_link": None,
    #     "pub_link": None,
    #     "other_links": [
    #         "https://doi.org/10.1063/1.4990503",
    #         "https://github.com/DescriptorZoo/sensitivity-dimensionality-results",
    #     ],
    # },
    "Silica_NPJCM_2022": {
        "new_name": "Silica_NPJCM_2022",
        "colabfit_id": "DS_w1hgczcfvmyd_0",
        "incar": None,
        "outcar": None,
        "data_link": "https://doi.org/10.5281/zenodo.6353683",
        "pub_link": "https://doi.org/10.1038/s41524-022-00768-w",
        "other_links": None,
    },
    "a-AlOx_JCP_2020": {
        "new_name": "a_AlOx_JCP_2020",
        "colabfit_id": "DS_17w6wkt656q2_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1063/5.0026289",
            "https://doi.org/10.24435/materialscloud:y1-zd",
        ],
    },
    "ANI-1x": {
        "new_name": "ANI_1x",
        "colabfit_id": "DS_4vquc2lauc66_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1038/s41597-020-0473-z",
            "https://doi.org/10.1063/1.5023802",
            "https://doi.org/10.1038/s41467-019-10827-4",
            "https://doi.org/10.1126/sciadv.aav6490",
            "https://doi.org/10.6084/m9.figshare.c.4712477.v1",
            "https://github.com/aiqm/ANI1x_datasets",
        ],
    },
    "Materials Project": {
        "new_name": "Materials Project",
        "colabfit_id": "DS_5q8sqx0nsg4j_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://materialsproject.org/",
            "https://doi.org/10.1063/1.4812323",
        ],
    },
    "JARVIS-C2DB": {
        "new_name": "JARVIS_C2DB",
        "colabfit_id": "DS_71f72a9w33i5_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1088/2053-1583/aacfc1",
            "https://jarvis.nist.gov/",
            "https://ndownloader.figshare.com/files/28682010",
        ],
    },
    "JARVIS_AGRA_CHO": {
        "new_name": "JARVIS_AGRA_CHO",
        "colabfit_id": "DS_6qgv9qmvwh91_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://github.com/Feugmo-Group/AGRA",
            "https://jarvis.nist.gov/",
            "https://figshare.com/ndownloader/files/41923284",
            "https://doi.org/10.1063/5.0140487",
            "https://doi.org/10.1021/acscatal.2c03675",
        ],
    },
    "JARVIS_AGRA_CO": {
        "new_name": "JARVIS_AGRA_CO",
        "colabfit_id": "DS_so1yqxbl6er1_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://github.com/Feugmo-Group/AGRA",
            "https://jarvis.nist.gov/",
            "https://figshare.com/ndownloader/files/41923284",
            "https://doi.org/10.1063/5.0140487",
            "https://doi.org/10.1021/acscatal.2c03675",
        ],
    },
    "JARVIS_AGRA_COOH": {
        "new_name": "JARVIS_AGRA_COOH",
        "colabfit_id": "DS_f6ahfjifyvww_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://github.com/Feugmo-Group/AGRA",
            "https://jarvis.nist.gov/",
            "https://figshare.com/ndownloader/files/41923284",
            "https://doi.org/10.1063/5.0140487",
            "https://doi.org/10.1021/acscatal.2c03675",
        ],
    },
    "JARVIS_AGRA_O": {
        "new_name": "JARVIS_AGRA_O",
        "colabfit_id": "DS_zwnmws5eqqdp_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://github.com/Feugmo-Group/AGRA",
            "https://jarvis.nist.gov/",
            "https://figshare.com/ndownloader/files/41923284",
            "https://doi.org/10.1063/5.0140487",
            "https://doi.org/10.1016/j.joule.2018.12.015",
        ],
    },
    "JARVIS_AGRA_OH": {
        "new_name": "JARVIS_AGRA_OH",
        "colabfit_id": "DS_qiy7gt62kg1s_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://github.com/Feugmo-Group/AGRA",
            "https://jarvis.nist.gov/",
            "https://figshare.com/ndownloader/files/41923284",
            "https://doi.org/10.1063/5.0140487",
            "https://doi.org/10.1016/j.joule.2018.12.015",
        ],
    },
    "JARVIS_ALIGNN_FF": {
        "new_name": "JARVIS_ALIGNN_FF",
        "colabfit_id": "DS_1vqk7eat02ef_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://ndownloader.figshare.com/files/38522315",
            "https://jarvis.nist.gov/",
            "https://github.com/usnistgov/alignn",
            "https://doi.org/10.1039/D2DD00096B",
        ],
    },
    "JARVIS-DFT-2D-3-12-2021": {
        "new_name": "JARVIS_DFT_2D_3_12_2021",
        "colabfit_id": "DS_cnq2rdn0yew6_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1038/s41524-020-00440-1",
            "https://jarvis.nist.gov/",
            "https://ndownloader.figshare.com/files/26808917",
        ],
    },
    "JARVIS_EPC_2D": {
        "new_name": "JARVIS_EPC_2D",
        "colabfit_id": "DS_xikcemv8af7u_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://figshare.com/ndownloader/files/38950433",
            "https://jarvis.nist.gov/",
            "https://doi.org/10.1021/acs.nanolett.2c04420",
        ],
    },
    "JARVIS_HOPV": {
        "new_name": "JARVIS_HOPV",
        "colabfit_id": "DS_rwb8fuu3dc3r_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1038/sdata.2016.86",
            "https://jarvis.nist.gov/",
            "https://ndownloader.figshare.com/files/28814184",
        ],
    },
    "JARVIS_mlearn": {
        "new_name": "JARVIS_mlearn",
        "colabfit_id": "DS_ta9ghetdl7qy_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://figshare.com/ndownloader/files/40424156",
            "https://jarvis.nist.gov/",
            "https://github.com/materialsvirtuallab/mlearn",
            "https://doi.org/10.1021/acs.jpca.9b08723",
        ],
    },
    "JARVIS_Materials_Project_84K": {
        "new_name": "JARVIS_Materials_Project_84K",
        "colabfit_id": "DS_hccnvn24txkq_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1063/1.4812323",
            "https://jarvis.nist.gov/",
            "https://ndownloader.figshare.com/files/24979850",
        ],
    },
    "JARVIS_Open_Catalyst_100K": {
        "new_name": "JARVIS_Open_Catalyst_100K",
        "colabfit_id": "DS_58bps5ff7hqa_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://github.com/Open-Catalyst-Project/ocp",
            "https://jarvis.nist.gov/",
            "https://figshare.com/ndownloader/files/40566122",
            "https://doi.org/10.1021/acscatal.0c04525",
        ],
    },
    "JARVIS_Open_Catalyst_10K": {
        "new_name": "JARVIS_Open_Catalyst_10K",
        "colabfit_id": "DS_s4c39yic066m_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://github.com/Open-Catalyst-Project/ocp",
            "https://jarvis.nist.gov/",
            "https://figshare.com/ndownloader/files/40566122",
            "https://doi.org/10.1021/acscatal.0c04525",
        ],
    },
    "JARVIS_OMDB": {
        "new_name": "JARVIS_OMDB",
        "colabfit_id": "DS_vtyvwqkgq7ou_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1002/qute.201900023",
            "https://jarvis.nist.gov/",
            "https://ndownloader.figshare.com/files/28501761",
        ],
    },
    "JARVIS-Polymer-Genome": {
        "new_name": "JARVIS_Polymer_Genome",
        "colabfit_id": "DS_uod49wjh6vt8_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1088/2053-1583/aacfc1",
            "https://jarvis.nist.gov/",
            "https://ndownloader.figshare.com/files/28682010",
        ],
    },
    "JARVIS_QM9_STD_JCTC": {
        "new_name": "JARVIS_QM9_STD_JCTC",
        "colabfit_id": "DS_nyxwfx2y43tj_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1038/sdata.2014.22",
            "https://jarvis.nist.gov/",
            "http://quantum-machine.org/datasets/",
            "https://ndownloader.figshare.com/files/28715319",
        ],
    },
    "JARVIS_QMOF": {
        "new_name": "JARVIS_QMOF",
        "colabfit_id": "DS_4pucd0z2bcxf_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1016/j.matt.2021.02.015",
            "https://jarvis.nist.gov/",
            "https://figshare.com/ndownloader/files/30972640",
        ],
    },
    "JARVIS_SNUMAT": {
        "new_name": "JARVIS_SNUMAT",
        "colabfit_id": "DS_d66futvfej5j_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1038/s41597-020-00723-8",
            "https://jarvis.nist.gov/",
            "https://www.snumat.com/",
            "https://ndownloader.figshare.com/files/38521736",
        ],
    },
    "JARVIS_TinNet_N": {
        "new_name": "JARVIS_TinNet_N",
        "colabfit_id": "DS_0kfmbe5bzsid_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://figshare.com/ndownloader/files/40934285",
            "https://jarvis.nist.gov/",
            "https://github.com/hlxin/tinnet/tree/master",
            "https://doi.org/10.1038/s41467-021-25639-8",
        ],
    },
    "JARVIS_TinNet_O": {
        "new_name": "JARVIS_TinNet_O",
        "colabfit_id": "DS_3gn3jdcbl6yb_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://figshare.com/ndownloader/files/40934285",
            "https://jarvis.nist.gov/",
            "https://github.com/hlxin/tinnet/tree/master",
            "https://doi.org/10.1038/s41467-021-25639-8",
        ],
    },
    "JARVIS_TinNet_OH": {
        "new_name": "JARVIS_TinNet_OH",
        "colabfit_id": "DS_11vg2wx5i8rs_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://figshare.com/ndownloader/files/40934285",
            "https://jarvis.nist.gov/",
            "https://github.com/hlxin/tinnet/tree/master",
            "https://doi.org/10.1038/s41467-021-25639-8",
        ],
    },
    "JARVIS-2DMatPedia": {
        "new_name": "JARVIS_2DMatPedia",
        "colabfit_id": "DS_us48xzuoctm5_0",
        "incar": None,
        "outcar": None,
        "data_link": None,
        "pub_link": None,
        "other_links": [
            "https://doi.org/10.1038/s41597-019-0097-3",
            "https://jarvis.nist.gov/",
            "https://ndownloader.figshare.com/files/26789006",
        ],
    },
}
