"""
ANI-1xBB ingest script for ColabFit VAST database.

Properties
----------
energy: total DFT energy in eV (converted from Hartree)
atomic-forces: forces in eV/Angstrom (converted from Hartree/Bohr)

File notes
----------
Source: vast_ingest/ani1xbb/bond_breaking_4el/*.npz
NPZ files are named by atom count (003.npz through 023.npz). Each contains
nonequilibrium conformers generated by an automated bond-breaking workflow.
Energies and forces were calculated at T_el = 0, 1000, and 5000 K using
B97-3c/ORCA 4.2.1 with Fermi smearing (FT-DFT). This script ingests the
primary T_el = 5000 K (b973c_etemp5000) energies and forces.

NPZ keys
--------
numbers: atomic numbers (uint8)
coord: atomic positions in Angstrom (float32)
charge: total charge (int8)
mult: spin multiplicity (uint8)
_id: geometry ID hex string (bytes, S24)
mol_id: parent molecule ID
smiles: SMILES of the initial molecule
scan_atoms: indices of the two stretched atoms (uint16)
iconf: step index within the stretching trajectory (uint16)
snap_source: 'opt' (constrained geometry optimization) or 'md' (NVT MD snapshot)
b973c_etemp5000.energy: B97-3c energy at T_el=5000K in Hartree (float64)
b973c_etemp5000.forces: atomic forces at T_el=5000K in Hartree/Bohr (float32)
b973c_etemp5000.fod: N_FOD fractional occupation density at T_el=5000K (float32)
"""

import os
from pathlib import Path

import numpy as np
from ase import Atoms as AseAtoms
from colabfit.tools.property_definitions import atomic_forces_pd, energy_pd
from colabfit.tools.vast.configuration import AtomicConfiguration
from colabfit.tools.vast.database import DataManager, VastDataLoader
from colabfit.tools.vast.property import PropertyInfo, PropertyMap
from dotenv import load_dotenv

load_dotenv()

access_key = os.getenv("VAST_DB_ACCESS")
access_secret = os.getenv("VAST_DB_SECRET")
endpoint = os.getenv("SPARK_ENDPOINT")

loader = VastDataLoader(
    access_key=access_key,
    access_secret=access_secret,
    endpoint=endpoint,
)
loader.config_table = "ndb.colabfit.dev.co_ani1xbb"
loader.config_set_table = "ndb.colabfit.dev.cs_ani1xbb"
loader.dataset_table = "ndb.colabfit.dev.ds_ani1xbb"
loader.co_cs_map_table = "ndb.colabfit.dev.cs_co_map_ani1xbb"

DATASET_ID = "DS_psm97yt0sles_0"
DATASET_NAME = "ANI-1xBB"
DESCRIPTION = (
    "ANI-1xBB is a dataset of approximately 13.1 million nonequilibrium "
    "conformers of small organic molecules (H, C, N, O only; up to 7 heavy "
    "atoms; up to 23 atoms total), designed to support the training of reactive "
    "machine learning interatomic potentials. Single-point quantum chemistry "
    "properties were computed at three electronic temperatures "
    "(T_el = 0, 1000, and 5000 K) using B97-3c composite DFT in ORCA 4.2.1 "
    "via finite-temperature DFT (Fermi smearing). All geometries were treated "
    "as closed-shell (charge = 0, mult = 1); Fermi smearing at T_el = 5000 K "
    "approximates the superposition of closed- and open-shell states during "
    "bond dissociation and is the primary labeling scheme used for model "
    "training in the associated publication. This dataset contains the T_el = 5000 K "
    "(b973c_etemp5000) energies and forces; data at T_el = 0 K and 1000 K are "
    "available in the original source files. Configuration sets represent: "
    "constrained geometry optimization steps (snap_source='opt', "
    "~9% of data) and fixed-distance NVT MD snapshots (snap_source='md', "
    "~91% of data)."
)

PUBLICATION = "https://doi.org/10.1021/acs.jctc.5c00347"
DATA_LINK = "https://kilthub.cmu.edu/articles/dataset/ANI-1xBB_dataset/28405316"
OTHER_LINKS = ["https://github.com/amateurcat/ANI-1xBB"]
PUBLICATION_YEAR = "2025"

AUTHORS = [
    "Shuhao Zhang",
    "Roman Zubatyuk",
    "Yinuo Yang",
    "Adrian Roitberg",
    "Olexandr Isayev",
]
LICENSE = "CC-BY-NC-ND-4.0"
DOI = None

DATA_PATH = Path(__file__).parent / "bond_breaking_4el"


def reader(data_path: Path):
    for npz_file in sorted(data_path.glob("*.npz")):
        data = np.load(npz_file, allow_pickle=True)
        n_confs = data["numbers"].shape[0]
        energies = data["b973c_etemp5000.energy"]  # Hartree
        forces = data["b973c_etemp5000.forces"]  # Hartree/Bohr

        numbers = data["numbers"]
        coords = data["coord"]
        ids = data["_id"]
        snap_sources = data["snap_source"]
        for i in range(n_confs):
            atoms = AseAtoms(
                numbers=numbers[i].astype(int),
                positions=coords[i],  # Angstrom
                pbc=False,
            )
            geom_id = ids[i].decode()
            snap_source = snap_sources[i]
            atoms.info = {
                "_name": f"{DATASET_NAME}__{snap_source}__{geom_id}",
                "energy": float(energies[i]),
                "forces": forces[i].tolist(),
                "snap_source": snap_source,
            }
            yield AtomicConfiguration.from_ase(atoms)


property_map = PropertyMap([energy_pd, atomic_forces_pd])

property_map.set_metadata_field("software", "ORCA 4.2.1")
property_map.set_metadata_field("method", "DFT-B97-3c")
property_map.set_metadata_field(
    "input",
    {
        "basis_set": "def2-mTZVP",
        "dispersion_correction": "D3BJ",
        "counterpoise_correction": "gCP",
        "electronic_temperature": "5000 K (Fermi smearing, FT-DFT)",
        "description": (
            "B97-3c composite DFT method with def2-mTZVP basis set, D3BJ "
            "dispersion correction, and geometric counterpoise (gCP) correction. "
            "Finite-temperature DFT (Fermi smearing) applied at T_el = 5000 K "
            "with all geometries treated as closed-shell (charge = 0, mult = 1). "
            "Geometries that failed FT-DFT SCF convergence were discarded. "
            "T_el = 5000 K was selected per the empirical formula "
            "T_el = 20000*a_x + 5000 (Grimme and Hansen), where a_x = 0 for "
            "B97-3c."
        ),
    },
)

energy_info = PropertyInfo(
    property_name="energy",
    field="energy",
    units="hartree",
    original_file_key="b973c_etemp5000.energy",
    additional=[("per-atom", {"value": False, "units": None})],
)
force_info = PropertyInfo(
    property_name="atomic-forces",
    field="forces",
    units="hartree/bohr",
    original_file_key="b973c_etemp5000.forces",
)
property_map.set_properties([energy_info, force_info])
PROPERTY_MAP = property_map.get_property_map()

gen = reader(DATA_PATH)

dm = DataManager(
    prop_defs=[energy_pd, atomic_forces_pd],
    configs=gen,
    prop_map=PROPERTY_MAP,
    dataset_id=DATASET_ID,
    standardize_energy=True,
    read_write_batch_size=10000,
)

dm.load_co_po_to_vastdb(loader, batching_ingest=True, check_existing=False)

dm.create_configuration_sets(
    loader=loader,
    name_label_match=[
        (
            f"{DATASET_NAME}__opt__.*",
            None,
            f"{DATASET_NAME}_Optimization",
            (
                "Conformers sampled from constrained geometry optimization steps "
                "of the bond-breaking workflow. At each elongation step the "
                "selected bond is held fixed while all other coordinates relax. "
                "Approximately 9% of the total dataset (1,225,522 conformers)."
            ),
            False,
        ),
        (
            f"{DATASET_NAME}__md__.*",
            None,
            f"{DATASET_NAME}_MD",
            (
                "Conformers sampled from fixed-distance NVT molecular dynamics "
                "simulations (1 ps, 0.5 fs time step, snapshots every 10 fs) "
                "performed after each geometry optimization step. Up to 10 "
                "snapshots selected per trajectory via a minimax diversity "
                "algorithm. Approximately 91% of the total dataset "
                "(11,919,355 conformers)."
            ),
            False,
        ),
    ],
)

dm.create_dataset(
    loader=loader,
    name=DATASET_NAME,
    authors=AUTHORS,
    publication_link=PUBLICATION,
    data_link=DATA_LINK,
    other_links=OTHER_LINKS,
    description=DESCRIPTION,
    data_license=LICENSE,
    publication_year=PUBLICATION_YEAR,
    equilibrium=False,
    date_requested="2026-05-22",
)
