"""
MSR-ACC-TAE25_Train ingest script for ColabFit VAST database.

Properties
----------
atomization-energy: total atomization energy at CCSD(T)/CBS (W1-F12) in eV

File notes
----------
Source: datasets--microsoft--msr-acc-tae25/blobs/
        4b30596e45e4b4c9842c53d2a7cbc50210bf21a8cb455bdfde0c953c99148898
        (71,871 rows; training split)

MSR-ACC/TAE25 provides 73,040 total atomization energies at the CCSD(T)/CBS
level using the W1-F12 thermochemical protocol (Molpro 2024.1) for closed-shell,
charge-neutral, covalently bound equilibrium molecules with up to 5 non-hydrogen
atoms from elements H–Ar (excluding rare gases). Geometries in the parquet file
are in bohr and are converted to Angstrom in the reader. TAE values are in
hartree in the source; colabfit-tools converts to eV during ingest.
"""

import os
from pathlib import Path

import pyarrow.parquet as pq
from ase import Atoms as AseAtoms
from ase.units import create_units
from colabfit.tools.property_definitions import atomization_energy_pd
from colabfit.tools.vast.configuration import AtomicConfiguration
from colabfit.tools.vast.database import DataManager, VastDataLoader
from colabfit.tools.vast.property import PropertyInfo, PropertyMap
from dotenv import load_dotenv

load_dotenv()

access_key = os.getenv("VAST_DB_ACCESS")
access_secret = os.getenv("VAST_DB_SECRET")
endpoint = os.getenv("SPARK_ENDPOINT")

loader = VastDataLoader(
    access_key=access_key,
    access_secret=access_secret,
    endpoint=endpoint,
)
loader.config_table = "ndb.colabfit.dev.co_mcc_tao25_trn"
loader.config_set_table = "ndb.colabfit.dev.cs_mcc_tao25_trn"
loader.dataset_table = "ndb.colabfit.dev.ds_mcc_tao25_trn"
loader.co_cs_map_table = "ndb.colabfit.dev.cs_co_map_mcc_tao25_trn"

DATASET_ID = "DS_yf2caw9gh4p7_0"
DATASET_NAME = "MSR-ACC-TAE25_Train"
DESCRIPTION = (
    "MSR-ACC/TAE25 (Microsoft Research Accurate Chemistry Collection, Total "
    "Atomization Energies 2025) provides 73,040 total atomization energies (TAEs) "
    "at the CCSD(T)/CBS level obtained with the W1-F12 composite wavefunction "
    "protocol implemented in Molpro 2024.1. "
    "This is the canonical training split comprising 71,871 molecules (99% of molecules "
    "remaining after removing overlap with the W4-17 and GMTKN55 benchmark sets)."
    "The dataset covers the chemical space "
    "of closed-shell, charge-neutral, covalently bound equilibrium molecular "
    "structures containing up to 5 non-hydrogen atoms drawn from elements H through "
    "Ar, excluding rare gases. Molecular structures were generated by exhaustive "
    "graph enumeration and degree-sequence sampling, then optimized through a cascade "
    "of GFN2-xTB, r2SCAN-3c, and B3LYP-D3(BJ)/def2-TZVPP levels of theory (ORCA). "
    "Structures were filtered to exclude those with significant multireference "
    "character (%TAE[(T)] > 6% at CCSD(T)/6-31G*), triplet electronic ground "
    "states, or dissociated fragments. The W1-F12 protocol includes Hartree-Fock "
    "extrapolation to the complete basis set limit (cc-pVDZ-F12 and cc-pVTZ-F12, "
    "alpha=5), CCSD-F12b correlation, perturbative triples delta(T) using "
    "jul-cc-pV(D+d)Z and jul-cc-pV(T+d)Z basis sets (alpha=3.22), and a "
    "core-valence correction using cc-pwCVTZ. The dataset spans 45.1% organic and "
    "54.9% inorganic molecules and provides broader chemical diversity than "
    "comparable datasets such as GDB-9 or VQM24/DMC. Additional data available "
    "in the source files, including DFT atomization energies at approximately 90 "
    "levels of theory, singlet-triplet gaps, %TAE[(T)] multireference diagnostics, "
    "and W1-F12 energy components, can be downloaded from ColabFit Exchange. "
)

PUBLICATION = "https://doi.org/10.1038/s41597-026-07200-8"
DATA_LINK = "https://huggingface.co/datasets/microsoft/msr-acc-tae25"
OTHER_LINKS = [
    "https://arxiv.org/abs/2506.14492",
    "https://zenodo.org/records/15783826",
]
PUBLICATION_YEAR = "2026"

AUTHORS = [
    "Sebastian Ehlert",
    "Jan Hermann",
    "Thijs Vogels",
    "Victor Garcia Satorras",
    "Stephanie Lanius",
    "Marwin Segler",
    "Klaas J.H. Giesbertz",
    "Derk P. Kooi",
    "Kenji Takeda",
    "Chin-Wei Huang",
    "Giulia Luise",
    "Rianne van den Berg",
    "Paola Gori-Giorgi",
    "Amir Karton",
]
LICENSE = "CDLA-Permissive-2.0"
DOI = None

UNITS = create_units("2014")
BOHR_TO_ANG = UNITS["Bohr"]

DATA_PATH = Path(
    "data/datasets--microsoft--msr-acc-tae25/blobs/4b30596e45e4b4c9842c53d2a7cbc50210bf21a8cb455bdfde0c953c99148898"
)


def reader(filepath):
    pf = pq.ParquetFile(filepath)
    for batch in pf.iter_batches():
        table = batch.to_pydict()
        for i in range(len(table["sha1"])):
            symbols = table["symbols"][i]
            positions = [[x * BOHR_TO_ANG for x in coord] for coord in table["geometry"][i]]
            atoms = AseAtoms(symbols=symbols, positions=positions, pbc=False)
            atoms.info = {
                "_name": f"{DATASET_NAME}__{table['sha1'][i]}",
                "tae": table["tae@w1-f12"][i],
                "sha1": table["sha1"][i],
                "molecular_charge": int(table["molecular_charge"][i]),
                "molecular_multiplicity": table["molecular_multiplicity"][i],
            }
            yield AtomicConfiguration.from_ase(atoms)


property_map = PropertyMap([atomization_energy_pd])
property_map.set_metadata_field("software", "Molpro 2024.1")
property_map.set_metadata_field("method", "W1-F12/CCSD(T)-CBS")
property_map.set_metadata_field(
    "input",
    {
        "basis_HF_CCSD": ("cc-pVDZ-F12 and cc-pVTZ-F12, CBS extrapolation alpha=5"),
        "basis_delta_T": ("jul-cc-pV(D+d)Z and jul-cc-pV(T+d)Z, extrapolation alpha=3.22"),
        "basis_core_valence": "cc-pwCVTZ",
        "geometry_optimization": "B3LYP-D3(BJ)/def2-TZVPP (ORCA)",
        "conformational_sampling": "GFN2-xTB then r2SCAN-3c",
        "multireference_filter": "%TAE[(T)] <= 6% at CCSD(T)/6-31G*",
        "spin_state_filter": "S0-T1 gap >= 0 at B3LYP/def2-TZVP",
    },
)
property_map.set_metadata_field("sha1", "sha1", dynamic=True)

tae_info = PropertyInfo(
    property_name="atomization-energy",
    field="tae",
    units="hartree",
    original_file_key="tae@w1-f12",
    additional=[("per-atom", {"value": False, "units": None})],
)
property_map.set_properties([tae_info])
PROPERTY_MAP = property_map.get_property_map()

gen = reader(DATA_PATH)

dm = DataManager(
    prop_defs=[atomization_energy_pd],
    configs=gen,
    prop_map=PROPERTY_MAP,
    dataset_id=DATASET_ID,
    standardize_energy=True,
    read_write_batch_size=10000,
)

dm.load_co_po_to_vastdb(loader, batching_ingest=True, check_existing=False)

dm.create_dataset(
    loader=loader,
    name=DATASET_NAME,
    authors=AUTHORS,
    publication_link=PUBLICATION,
    data_link=DATA_LINK,
    other_links=OTHER_LINKS,
    description=DESCRIPTION,
    data_license=LICENSE,
    publication_year=PUBLICATION_YEAR,
    equilibrium=True,
    date_requested="2026-05-11",
)
